### ISSUE TITLE
Does not work in IE

### ISSUE THREAD

**Issue by abobwhite** [estheban/node-json2xml#17]
I know, I know. We all hate IE. But this just flat out doesn't work in IE and people still need to use it. For the record, I'm using IE11.

 I believe I've pinned it down to the fact that ```json.constructor.name``` is undefined in IE so it always hits the else block. I think this can be relieved by changing:

```
if(type==='Array'){
  ......
} else if (type ==='Object' && typeof json === "object") {
  ...........
} else {}
```

to

```
if(!!json.length && typeof json !== 'string'){
  ......
} else if (typeof json === "object") {
  ...........
} else {}
```

What do you think? I'm happy to make a PR.

**Comment by abobwhite** [comment]
PR created: https://github.com/estheban/node-json2xml/pull/18

**Comment by estheban** [comment]
PR merged
